---
title: 投资研究笔记（一）：宏观经济的分析框架
author: 令纪泽
date: '2023-09-10'
slug: ''
categories:
  - Work
tags:
  - 资产配置
  - 宏观经济
---

目前对于各个大类资产的配置若按照“自上而下”的研究方法，就不得不涉及到宏观经济的分析。

如何看宏观经济的运行情况，主要要关注四个方面：
1. 经济增长动力：包括消费、投资、政府购买与对外贸易
1. 经济运行情况：包括GDP、物价水平、人口、就业、景气度、工业生产等
1. 政府财政：财政政策、税收情况与政策、财政收支平衡等
1. 金融信贷：利率与信贷、货币市场、证券市场等

经济运行分类下提供中国经济运转现状的说明与指标，从价与量方面全方位洞悉经济发展的现状；增长动力分类则更多的留意为经济增速提供支持的三大主要方面关注经济总量提升的动力，更关注人民生活水平；金融信贷分类是对货币，金融与信贷的整合。关注政府在货币政策层面的引导，也体现市场融资与利率，汇率水平的反馈；政府财政分类侧重对税收与财政收支的汇总与解读。财政预算，赤字经营以及地方政府财政的独立与自给程度。

# 经济运行
### 景气与物价
- 对于整个经济的景气情况，重点关注**PMI**指标，尤其是在工业占比较大、产出增加较多的情况下，特别需要关注**制造业PMI**，比较与50枯荣线的关系。

- 物价方面，重点关注CPI状况，CPI分项中波动性最大的是食品项，其中以菜价与猪肉价的波动性最大。

- GDP平减指数是反应国内通胀水平的重要指征，若GDP平减指数继续下行，也将引发更多对于宽松货币政策的预期。

### 经济运行

- 人口与就业：决定我国中长期经济增长的核心变量是人口结构及城镇化进程。

### 增长动力

#### 消费
- 关注社会消费品零售总额以及其结构（日用品、石油及制品、汽车等等）
- 关注人均可支配收入及结构

#### 投资
- 主要关注制造业、基建和房地产投资增速
- 10年期国债收益率是固投值增速的风向标

### 金融信贷

- M2的增长可能表明经济活动增强，信贷扩张，或者中央银行采取了宽松的货币政策。

- M2增长的驱动因素：信贷创造——银行通过发放贷款创造存款，是M2增长的主要来源；财政存款——政府的财政收支情况会影响M2。财政存款的增加会减少M2，而财政支出的增加会增加M2；外汇占款——中央银行购买外汇时会释放基础货币，增加M2；非银金融机构存款——非银行金融机构的存款也计入M2，其变化会影响M2的总量。

- M1-M2剪刀差：当M1增速大于M2增速时，即出现正剪刀差，这通常意味着消费需求旺盛，有物价上涨的预期，存款活期化，活钱增多。这种情况下，企业对未来持乐观态度，增加流动性；相反，当M2增速大于M1增速时，即出现负剪刀差，这表明大家倾向于储蓄而不是消费，经济可能相对冷淡。在这一时期，对货币的需求较少，企业和个人的存款定期化倾向较高。M1-M2剪刀差的变化还可以作为经济活动和市场资金流向的先行指标。例如，当M1-M2剪刀差从负转为正，并逐步增强时，是经济回暖的关键信号。此外，M1-M2剪刀差与股市走势呈正相关，当剪刀差扩大时，意味着更多的资金流向股市，可能预示着股市有机会。

- 关注社融增速：社融增速代表的是社会融资规模的同比增长速度，即一定时期内实体经济从金融体系获得的资金总额的增长率。社会融资（社融）是指实体经济（境内非金融企业和住户）从金融体系获得资金的活动，这里的金融体系包括银行、证券、保险、信托等金融机构，以及信贷市场、债券市场、股票市场、保险市场以及中间业务市场等。社融增速是衡量经济融资需求和金融体系支持实体经济能力的重要指标，它反映了金融体系对实体经济的资金支持程度和经济增长的潜力。社融增速的变化可以反映金融市场的资金流向和经济活动的扩张或收缩情况。例如，如果社融增速持续高于名义GDP增速，可能表明居民投资意愿提高，企业依赖信贷发展，同时金融产品不断创新，监管趋于宽松。这种情况下，社融增速的提升有助于拉动经济增长，提高资金利用效率。然而社融增速的过快增长也可能带来一些风险，如资产泡沫、信贷风险增加等。

- 国际收支平衡：国际收支平衡严重依赖于国际资本的流入，外资流入对人民币汇率及境内资产价格的影响有不可忽视的作用。除了与贸易与劳务收支紧密相关的经常项之外，以外资买股买债资金为典型代表的资本项下近年来也有持续的资金入账，这主要得益于我国资本市场开放政策，境外央行等配置型资金仍将继续增持人民币债券，且FDI资金流入也略好于预期。 但后期随着美联储进入加息周期，资金成本的提高或者中美利差的收窄将使得国际资金回流发达国家经济体，从而对国内的流动性和汇率试压。人民币汇率的走势一方面取决于中美两国基本面预期的此消彼长，一方面来自央行的干预意愿。2018年，美元指数大幅走强，虽然同期人民币受到的冲击有限，但新兴货币汇率纷纷大幅贬值导致中国的外需环境随之恶化。 全球经济增速下滑后，资金往往回流美国支撑美元上涨。而人民币汇率弱势与强势之间转换则主要决定于美元指数为代表的篮子货币的走势，一旦美元指数冲高回落，则人民币可能摆脱弱势出现阶段性走强。此外，一年期人民币NDF对人民币走势有较好的领先作用。

### 政府财政

- 关注税收收入增速及结构（增值税、个人所得税及企业所得税）

- 关注关税收入与进口额的增速

- 关注地方政府城投债的信用利差