---
title: 基金研究笔记（七）：公募基金、私募基金的投资策略（一）
author: ''
date: '2024-04-20'
slug: ''
categories:
  - Work
tags:
  - 基金
---

下文中的基金指的均是“证券投资基金”，与“股权投资基金”不同。

# 公私募基金的区别:

最直接的区别就是定义中的“是否公开发行”。

可以从下面几个维度进行比较：
  
  - 投资门槛
  - 资金容量
  - 监管合规
  - 投资策略
  - 公司管理与投研体系
  - ...
  
## 投资策略分类

根据不同的角度，可以将投资策略分为两类：从投资方式来说，可以分为主动投资和被动投资；从策略的实现手段来说，可以分为主观投资和量化投资。

主动投资和被动投资的区别在基金经理的策略是否能获得所谓的 $\alpha$ ，即超越基准的收益；而被动投资大多是指数型投资，即复制某项指数成分并持续跟踪，获得 $\beta$ 收益。主动型基金在市场产品中占大多数，但由于 $\alpha$ 策略的不稳定，且难以获得的事实，近年来相当数量的主动型基金产品并没有跑赢指数基准。因此，由于主动基金超额收益获取愈发困难，管理费相对于被动产品较高，近年来被动产品，指数化投资逐渐形成趋势，份额不断上升。

主动投资在公私募市场上均较为常见，而指数基金（主要是ETF、LOF之类的产品）主要由公募基金发行。

主观投资与量化投资是两种投资思路（或者说是投资手段），近年的业绩来看，两者平分秋色，各有千秋。

主观投资有着较为固定的研究框架，研究“宏观——行业——公司”，最后由分析框架与经验判断进行资产选择与择时，投资的资产包括权益类（股票、可转债）、固收类（主要是债券）、商品等。

而量化投资偏重于数据驱动发掘市场投资机会，并结合衍生品构造较为复杂的资产组合，实现精准获得收益，分散风险。投资的资产包括权益类、固收类、金融衍生品等。


<div style='display: none'> 
|  | 主动投资 | 被动投资 |
| :--: | :--: | :--: |
| 主观投资 | 行业精选、全市场精选、纯债、固收+、FOF等 | 指数型ETF、LOF等 |
| 量化投资 | 多因子选股、趋势跟踪等 |  --|
</div > 

下面，分资产类别简要归纳各类资产主要且常见的投资策略：

<div style='display: none'> 
|  | 公募基金 | 私募基金 |
| :--: | :--: | :--: |
| 权益类 | 主观选股、量化选股、指数增强、量化对冲、指数型ETF、LOF等 | 主观选股、量化选股、指数增强、量化对冲、市场中性、多空等 |
| 固收类 | 久期管理、信用下沉、波段操作 | 久期管理、信用下沉、波段操作（量化） |
| 衍生品 | --（基本少见，有一些商品类指数跟踪） | 主观CTA、量化CTA、期权波动率、套利等 |
| 另类投资 | REITs |  -- |

</div>

| 投资标的 | 公募基金 | 私募基金 |
| --- | --- | --- |
| 权益类 | 主观选股、量化选股、指数增强、股票ETF（包含行业ETF、主题ETF等）、LOF、行业轮动、事件驱动、主题投资等 | 主观选股、量化选股、指数增强、对冲套利（含统计套利、事件套利等）、市场中性、多空策略等 |
| 固收类 | 久期管理、信用下沉、波段操作（含国债期货等利率衍生品对冲工具） | 久期管理、信用下沉、信用债投资策略（高收益债、民企债等）、波段操作（包含量化策略的利率债波段交易）*固收类私募目前较少* |
| 衍生品 | 股指期货、国债期货的套利、对冲交易（较少直接作为产品，但可能作为工具使用） | 主观CTA、量化CTA、期权波动率交易、套利策略（含跨期套利、跨品种套利、跨市场套利等）、股票对冲策略（如股票多空策略）等 |
| 另类投资 | REITs等 | 艺术品投资（较为少见，马未都）、房地产直接投资、基础设施投资、不良资产投资等 |


  